import assert from 'node:assert/strict';
import {createEnergy} from './src/energy.js';
const energy=createEnergy();
for(let i=0;i<10;i++)assert.equal(energy.update(0.5,true,true),true);
assert.equal(energy.state.value,0);
assert.equal(energy.update(0.5,true,true),false);
assert.equal(energy.state.value,0);
energy.update(1,false,true);
assert.equal(energy.state.value,0);
energy.update(2,false,true);
assert.equal(energy.state.value,25);
assert.equal(energy.update(0.1,true,true),true);
assert.equal(energy.state.value,23);
energy.update(10,false,true);
assert.equal(energy.state.value,100);
energy.update(10,true,false);
assert.equal(energy.state.value,100,'Holding Shift while stationary must not drain energy');
energy.update(1,true,true);energy.reset();
assert.equal(energy.state.value,100);assert.equal(energy.state.exhausted,false);
console.log('PASS: sprint drain, exhaustion, recovery delay, walking recovery, stationary Shift, restart reset');
